# Jekyll! config

# Site settings
title: UASF Working Group

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true

# Sass style
sass:
  style: compressed

# Site theme
theme: jekyll-theme-minimal
